apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewogICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAiYXV0aCI6ICJiV05tTVRGNU9tZG9jRjluVHpnMWJHNUhWSE5pYTNCRGJrbHlaemQ2YzFwSlYxZDJiR3QxUVZZellqbHNPRkE9IgogICAgICAgIH0KICAgIH0sCgkiY3VycmVudENvbnRleHQiOiAiY29saW1hIgp9Cg==
type: kubernetes.io/dockerconfigjson
